import { BriefcaseBusiness, Clock3, MessageCircleReply, PhoneCall, Target, Trophy } from "lucide-react";
import { requireAuth } from "@/src/server/auth";
import { getDashboardData } from "@/src/server/services/crm-query-service";
import { PageHeader } from "@/src/components/ui/page-header";
import { StatCard } from "@/src/components/ui/stat-card";
import { TrendChart } from "@/src/components/dashboard/trend-chart";

export const metadata = { title: "Relatórios" };

export default async function ReportsPage({ searchParams }: PageProps<"/relatorios">) {
  const context = await requireAuth();
  const query = await searchParams;
  const dashboard = await getDashboardData(context, { days: Number(query.days) || 30 });
  const { volumes, rates } = dashboard;
  return <div className="space-y-6"><PageHeader eyebrow="Análise comercial" title="Relatórios" description="Volumes, taxas e conversão calculados a partir do histórico real de atividades." actions={<form className="flex gap-2"><select className="field" name="days" defaultValue={String(dashboard.period.days)}><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option><option value="180">180 dias</option></select><button className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Aplicar</button></form>} /><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="Leads importados" value={volumes.imported} icon={BriefcaseBusiness} /><StatCard label="Tentativas" value={volumes.attempts} icon={PhoneCall} /><StatCard label="Respostas" value={volumes.responses} icon={MessageCircleReply} tone="green" /><StatCard label="Vencidos" value={volumes.overdue} icon={Clock3} tone="amber" /><StatCard label="Interessados" value={volumes.interested} icon={Target} tone="purple" /><StatCard label="Reuniões" value={volumes.meetings} icon={Target} tone="purple" /><StatCard label="Propostas" value={volumes.proposals} icon={BriefcaseBusiness} /><StatCard label="Vendas" value={volumes.wins} icon={Trophy} tone="green" /></div><div className="grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><section className="card p-5 sm:p-6"><h2 className="font-semibold text-slate-900">Evolução diária</h2><TrendChart data={dashboard.trend} /></section><section className="card p-5 sm:p-6"><h2 className="font-semibold text-slate-900">Taxas consolidadas</h2><div className="mt-5 space-y-5">{[["Contato", rates.contact, `${volumes.effectiveContacts}/${volumes.assigned}`],["Resposta", rates.response, `${volumes.responses}/${volumes.effectiveContacts}`],["Conversão", rates.conversion, `${volumes.wins}/${volumes.worked}`]].map(([label,rate,volume]) => <div key={String(label)}><div className="flex justify-between"><span className="text-sm text-slate-600">{label}</span><strong>{Number(rate).toFixed(1)}%</strong></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand-500" style={{ width: `${Math.min(Number(rate),100)}%` }} /></div><p className="mt-1 text-xs text-slate-400">Volume: {volume}</p></div>)}</div></section></div><section className="card p-5 sm:p-6"><h2 className="font-semibold text-slate-900">Funil consolidado</h2><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{dashboard.funnel.map((stage) => <div key={stage.id} className="rounded-xl border p-4"><div className="flex items-center gap-2"><span className="size-3 rounded-full" style={{ backgroundColor: stage.color }} /><span className="text-sm font-medium text-slate-700">{stage.name}</span><strong className="ml-auto tabular-nums">{stage.count}</strong></div></div>)}</div></section></div>;
}
